### ISSUE TITLE
Hostname is not correctly shown in New Relic dashboard when using docker

### ISSUE THREAD

**Issue by haandude** [kamon-io/kamon-newrelic#11]
I have made my own local fork and we have updated our components to allow for optional config parameter for Dockerized applications, to pass hostname via an environment variable to correctly show the hostname in the New Relic dashboard.

Would it be appreciated if i contribute this change to the project?

**Comment by haandude** [comment]
See my commit in the github fork: https://github.com/haandude/kamon-newrelic/commit/fcf6c002825ff4f00dab0d80728062d27a629516

**Comment by jasonjkeller** [comment]
@dpsoft @ivantopo Can this issue be closed since it relates to the old New Relic Reporter that has since been replaced?
