### ISSUE TITLE
Publish new version of the Kamon New Relic Reporter

### ISSUE THREAD

**Issue by jasonjkeller** [kamon-io/kamon-newrelic#14]
Can we get the updated version of the New Relic Reporter published? I assume that it will simply be published to the same maven coordinates that the previous version of the reporter was? https://mvnrepository.com/artifact/io.kamon/kamon-newrelic

It probably makes sense to publish the `1.0.0` version at this point.

We should also update the readme to accurately reflect the newly published artifact name as well.

**Comment by jasonjkeller** [comment]
@dpsoft @ivantopo If there is anything you need from us to help move this forward please let us know. Thanks!

**Comment by dpsoft** [comment]
@jasonjkeller I've just released the version `1.0.0` https://bintray.com/kamon-io/releases/kamon-newrelic/1.0.0 and is on his way to maven central.

**Comment by jasonjkeller** [comment]
Thanks @dpsoft !
