### ISSUE TITLE
Replace new relic agent dependency with new relic api

### ISSUE THREAD

**Issue by danielkman** [kamon-io/kamon-newrelic#2]
Kamon-newrelic is dependent on the newrelic agent jar, but it seems to only be using the error reporting functionality which can be done using the newrelic-api jar instead.

The api jar is much more lightweight and causes less issues when trying to combine the kamon-newrelic dependency into a fat jar

**Comment by jkwatson** [comment]
Even better would be to use New Relic's new public metric APIs to get this data into the backend. https://docs.newrelic.com/docs/data-ingest-apis/get-data-new-relic/metric-api/introduction-metric-api
