### ISSUE TITLE
NR Metric Reporting Throwing UnsupportedContentType Exceptions

### ISSUE THREAD

**Issue by peteaxt** [kamon-io/kamon-newrelic#3]
The metric reporter has started throwing this exception: spray.httpx.PipelineException: UnsupportedContentType(Expected 'application/json' or 'text/plain')

Looks like the response type from NR change to text/json, updating JsValueUnmarshaller in ApiMethodClient to include the custom media type `MediaType.custom("text/json")` has fixed the issue for me.

**Comment by bradleyfalk** [comment]
I've confirmed this is indeed the issue and solution. I'm happy to create a pull request for this for the next release

**Comment by dpsoft** [comment]
@bradleyfalk please, go ahead and submit the PR :),

**Comment by bradleyfalk** [comment]
branch is ready, but I'll need permission to push.

**Comment by dpsoft** [comment]
please make a fork and then you can do a PR

**Comment by iamthiago** [comment]
please, do it and generate a new version :)

**Comment by dpsoft** [comment]
@bradleyfalk @thiagoandrade6 I've just released the `0.6.7` version in our bintray repository: https://bintray.com/kamon-io/releases/kamon-newrelic

**Comment by iamthiago** [comment]
Thank you @dpsoft and @bradleyfalk
