### ISSUE TITLE
Proxy Client Support?

### ISSUE THREAD

**Issue by synox** [kamon-io/kamon-newrelic#7]
How can this be used with a proxy?  -Dhttp.proxyHost... does not work for me. 

Versions: 
akka: 2.5.1
io.kamon:kamon-core_2.11:0.6.0
org.aspectj:aspectjweaver:1.8.10
io.kamon:kamon-newrelic_2.11:0.6.7

**Comment by peng-sun** [comment]
Hi. No one answer? I have the same problem.

**Comment by dpsoft** [comment]
@synox @peng-sun currently we haven't any cpu cycle for assign to this issue, but as always PR are welcome ;).

**Comment by peng-sun** [comment]
@synox @dpsoft I double checked and made it work. My situation needs to set -Dhttps.proxyHost and -Dhttps.proxyPort. Should be safe to set both http and https java properties if you proxy supports that.

**Comment by jasonjkeller** [comment]
@dpsoft @ivantopo Can this issue be closed since it relates to the old New Relic Reporter that has since been replaced?

**Comment by synox** [comment]
I don't need this feature any more.
