### ISSUE TITLE
Report error to newrelic for 5xx response?

### ISSUE THREAD

**Issue by peng-sun** [kamon-io/kamon-newrelic#9]
My testing result is that kamon-newrelic does not report error to newrelic for 5xx response (need expert's confirmation). I saw following comments for https://github.com/kamon-io/Kamon/blob/master/kamon-core/src/main/scala/kamon/util/http/HttpServerMetrics.scala. So the error info can be got from metrics. Any hint on how to achieve that?

/**
 *  Counts HTTP response status codes into per status code and per trace name + status counters. If recording a HTTP
 *  response with status 500 for the trace "GetUser", the counter with name "500" as well as the counter with name
 *  "GetUser_500" will be incremented.
 */

**Comment by ivantopo** [comment]
Hello there! I can confirm that those errors are not being reported to NewRelic. If you add the [NewRelicErrorLogger](https://github.com/kamon-io/kamon-newrelic/blob/master/src/main/scala/kamon/newrelic/NewRelicErrorLogger.scala) to your `akka.loggers` configuration and the errors generating the 5xx response are being logged through the ActorSystem bus then you will see them in NewRelic.

We do recognize how limited this is, but that's what is available at the moment :(

**Comment by peng-sun** [comment]
@ivantopo I tested and it works. It's so helpful, exactly what I need. Thanks a lot for providing the solution.
